services:
  - type: web
    name: ward-3-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
